### ISSUE TITLE
Incorrect creatures images

### ISSUE THREAD

**Issue by Hokan-Ashir** [Hokan-Ashir/SFGameDataEditor#21]
- Units/Trolls - the "Smasher Upgrade" and "Bouncer Upgrade" are reverse.
Fixed
- Gonthar Thorme, had a wrong picture. The real picture of Gonthar is a Recruit not a Enchanter.
Fixed
- Briarwolves recruit had a wrong picture, is not a mentalist.
Fixed
- I spot a wrong picture at the section Treelife Deamons, The Red Butcher, is not a Ice Elves Worker.
Fixed
- A lot of pictures is missing for the Screamers and Luciens
Fixed

**Comment by Hokan-Ashir** [comment]
@Berzetoberze, what actually Recruit picture Gonthar Thorme should have? With Red/Green/Blue skin?

**Comment by Hokan-Ashir** [comment]
Also @Berzetoberze, what is actually the correct image of Briarwolves recruit? Is it red-skinned or green-skinned recruit picture?

**Comment by Berzetoberze** [comment]
For Gonthar = Green
For Recruit = Red

**Comment by Hokan-Ashir** [comment]
@Berzetoberze it was a Red Legion recruit after all =)
Nonetheless, I've fixed it already

**Comment by Hokan-Ashir** [comment]
Hi @Berzetoberze, I've added all images that I had and fixed images issues that you've found
Let me know, if you find anything new =)
