### ISSUE TITLE
Editing texture

### ISSUE THREAD

**Issue by Sorvina18** [Hokan-Ashir/SFGameDataEditor#42]
Hello Hokan Ashir

I was asking myself if your Game data editor was able to change elves textures to the ice elves texture.

**Comment by Hokan-Ashir** [comment]
Hi Sorvina,

Editor can change "body" part of any NPC you can find in the game. So you can change "model" of, lets say, NPC "Blade Destroyer" to "Blade Principal". So it will look like Blade Principal, but will attack like Blade Destroyer.
Stricktly speaking this is not "texture change" but more "model change"

Also you can find corresponsing texutre name in <folder_where_game_installed>/texutres, that describes elves  texutres, copy ice elves texutre and change its name to elves' name texutre.
Be careful not to change, lets say, Fealinde's texture (aka Elves Druid) to Ice Elves Protector; texute will be applied to model but will look-a-like monster from hell =)

**Comment by Sorvina18** [comment]
Omg it's wonderful !
But I really think i'm gonna need a step by step tutorial , i'm so lost in all this .pak files x_x

**Comment by Hokan-Ashir** [comment]
You don't need *.pak files to swap or duplicate textures, find desirable *.dds file (you can preview *.dds files with i.e. - https://www.nvidia.ru/object/windows_texture_viewer.html) and copy it with renaming or swap desirable file names

**Comment by Sorvina18** [comment]
Thank you but the problem is that I don't have .dds files I only have .pak and I must unpack it with dragon unpacker to have the .dds files, and the game don't run when the .pak are unpacked...

Do you think I must unpacke, rename the desirable .dds and repack then ? And is it possible ?

**Comment by Hokan-Ashir** [comment]
I don't personally recall *.pak files in "texture" folder of the game
What version of the game do you have?
I don't have preinstalled game at my disposal, so could you please post screenshots of your "textures" folder? I guess we're missing something =)

**Comment by Sorvina18** [comment]
Here's a screen : https://www.zupimages.net/up/18/34/pxtj.png
As you can see I only have .pak that I must unpack to reach the textures.

But now it's ok I just found how to do it ! We just have to put the renamed file in Spellforce directory just like a mod.

Exemple : You found figure_npc_elf_ranger_ice_id1 (ice elf npc)  and replace the name by figure_elf_ranger_cold_id1 (normal ranger) , you place the edited .dds file in Spellforce directory and the elf ranger will be replace in the game by the ice elf ranger ! :D
