### ISSUE TITLE
hi pls help i dont understand editor how can work i run editor with java open game file opened but not work i m playin spellforce platinum edition on steam

### ISSUE THREAD

**Issue by jamathar** [Hokan-Ashir/SFGameDataEditor#43]
hi pls help i dont understand editor how can work i run editor with java open game file opeed select languege and search file i opened file download data and first screen table item spell etc.but spell or any click dont do anything sry bad english.how can be do it

**Comment by Hokan-Ashir** [comment]
To clarify:

1. You've downloaded last version of editor (which is alpha-9 - 'Editor-alpha-9 .jar') from here https://github.com/Hokan-Ashir/SFGameDataEditor/tree/master/Editor/bin
2. Selected language
3. Selected file
4. You can see main screen with spells, items etc., but clicks simply not working on any place in the app

Do I understand you correctly?

**Comment by jamathar** [comment]
Thank you for your interest. my main problem begins with making the game's mod file. I am using windows 10.create sf-mode or. it doesn't change with the cff file and it doesn't work if I delete the original file. windows are necessarily involved in the program with an "open together" .jpeg .mpeg vs.i dont understand pls help thx alll

 

Geri bildirim gönder

Geçmiş

Kaydedilenler

Topluluk

**Comment by jamathar** [comment]
thx for all ur editor is crazzy i done it my problem i change file format custom file extension .mod to .cff :D

**Comment by Hokan-Ashir** [comment]
You're very welcome, glad to hear you like the Editor and you solved your issue =)
