### ISSUE TITLE
It doen't work

### ISSUE THREAD

**Issue by IMordovin** [Hokan-Ashir/SFGameDataEditor#44]
Hi!
After launch editor 8 in java I can see main screen with spells, items,races etc., but clicks simply not working on any place in the app.

Can u help me?

**Comment by Hokan-Ashir** [comment]
Hi, can you post here content of log file that appears next to jar file?

Also try using 9th version of editor and pls post what OS you're launching
editor onto

чт, 11 апр. 2019 г., 13:17 IMordovin <notifications@github.com>:

**Comment by Hokan-Ashir** [comment]
Figured out, @IMordovin didn't able to run it correctly

Closing issue
